#!/bin/bash

# Script to help download the WordPress export file
# This should be run by the user on their local machine

echo "WordPress Import Helper Script"
echo "==============================="
echo ""
echo "Step 1: Download the WordPress export file"
echo ""
echo "Please download the file manually from:"
echo "https://github.com/pellauri/mortabackup/blob/import-wp/martesdemorta.WordPress.2024-06-05.xml"
echo ""
echo "Click the 'Raw' button or 'Download' button to save the file."
echo ""
echo "Step 2: Save the file"
echo ""
echo "Save the file as: martesdemorta.WordPress.2024-06-05.xml"
echo "Place it in the root directory of this project."
echo ""
echo "Step 3: Run the import"
echo ""
echo "Once you have the file, run:"
echo "  npm run import-wordpress martesdemorta.WordPress.2024-06-05.xml"
echo ""
echo "Or directly with Node:"
echo "  node import-wordpress.js martesdemorta.WordPress.2024-06-05.xml"
echo ""
echo "==============================="
echo ""
echo "If you have access to the pellauri/mortabackup repository,"
echo "you can also try cloning it directly:"
echo ""
echo "  git clone https://github.com/pellauri/mortabackup.git /tmp/mortabackup"
echo "  cd /tmp/mortabackup"
echo "  git checkout import-wp"
echo "  cp martesdemorta.WordPress.2024-06-05.xml $(pwd)/"
echo ""
echo "Then run the import from your project directory."
echo ""
